name: Build and Deploy to S3 using Terraform

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Project
        working-directory: frontend
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Run Terraform Init
        working-directory: terraform/dev
        run: terraform init

      - name: Run Terraform Plan
        working-directory: terraform/dev
        run: terraform plan -var="s3_bucket_name=${{ vars.BUCKET_NAME }}"

      - name: Run Terraform Apply
        working-directory: terraform/dev
        run: terraform apply -var="s3_bucket_name=${{ vars.BUCKET_NAME }}"
